version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    ports:
      - 3306:3306
    volumes:
      - /home/shehpepapig/bdd:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  back-app:
    image: back-app:latest
    restart: always
    build:
      context: ShehPepapig/back/
    ports:
      - 8887:8080

  front-app:
    image: front-app:latest
    restart: always
    ports:
      - 80:8080
    build:
      context: ShehPepapig/FrontEnd/
